export { default as Home } from "./Home.jsx";
export { default as About } from "./About.jsx";
export { default as Gallery } from "./Gallery.jsx";
export { default as Contact } from "./Contact.jsx";
export { default as Order } from "./Order.jsx";
export { default as TrackOrder } from "./TrackOrder.jsx";
export { default as Login } from "./Login.jsx";
export { default as Register } from "./Register.jsx";
export { default as Dashboard } from "./Dashboard.jsx";